import { LegalPage, Lead, H2, H3, P, UL } from '../components/LegalPage.jsx'

export default function Privacy() {
  return (
    <LegalPage eyebrow="Legal" title="Privacy Policy" updated="March 6, 2026">
      <Lead>
        FluentLanguage.net is operated by Isela Bingham, a professional Spanish
        interpreter and translator based in Stockton, California. This Privacy
        Policy explains what personal information we collect, how we use it, and
        your rights — including rights under the California Consumer Privacy Act
        (CCPA) and the California Privacy Rights Act (CPRA).
      </Lead>

      <H2>1. Who We Are</H2>
      <P>
        <strong>Business Name:</strong> FluentLanguage.net (Isela Bingham)
        <br />
        <strong>Location:</strong> Stockton, California, USA
        <br />
        <strong>Contact:</strong> ibingham@compuprotech.com
      </P>

      <H2>2. Information We Collect</H2>
      <P>
        We collect personal information only when you voluntarily provide it
        through our website forms or when it is automatically generated by
        standard server operations.
      </P>
      <H3>Information You Provide</H3>
      <UL>
        <li>
          <strong>Contact Form:</strong> Your name, email address, and message
          content when you submit a quote or inquiry request.
        </li>
        <li>
          <strong>Review Form:</strong> Your name (optional), email address, star
          rating, and written review when you submit a client testimonial.
        </li>
      </UL>
      <H3>Information Collected Automatically</H3>
      <UL>
        <li>
          <strong>Server Logs:</strong> Your IP address, browser type, operating
          system, referring URL, pages visited, and date/time of visit. This is
          standard web server logging and is not used for profiling or
          advertising.
        </li>
      </UL>
      <H3>What We Do Not Collect</H3>
      <P>
        We do not use cookies, tracking pixels, web beacons, or analytics
        software. We do not collect payment information — all billing is handled
        outside this website. We do not collect sensitive personal information
        such as Social Security numbers, government-issued ID, financial account
        numbers, or health information through this website.
      </P>

      <H2>3. How We Use Your Information</H2>
      <P>We use the information you provide solely for the following purposes:</P>
      <UL>
        <li>To respond to your inquiry or quote request.</li>
        <li>
          To display your review on this website (name and review text only —
          your email is never published).
        </li>
        <li>
          To send you a confirmation or follow-up communication related to your
          submission.
        </li>
        <li>To maintain the security and proper operation of this website.</li>
      </UL>
      <P>
        We do not use your information for marketing, advertising, profiling,
        automated decision-making, or any purpose beyond direct communication
        related to your inquiry or review.
      </P>

      <H2>4. How We Share Your Information</H2>
      <P>
        We do not sell, rent, trade, or share your personal information with third
        parties for their own use. Your information may be shared only in the
        following limited circumstances:
      </P>
      <UL>
        <li>
          <strong>Email Delivery (Resend, Inc.):</strong> When you submit a
          contact or review form, your email address is passed to Resend, Inc. —
          our transactional email service provider — solely for the purpose of
          delivering your submission confirmation. Resend acts as a data processor
          on our behalf and does not use your data for its own purposes. Resend's
          privacy policy is available at resend.com.
        </li>
        <li>
          <strong>Legal Obligation:</strong> We may disclose information if
          required by law, court order, or governmental authority.
        </li>
      </UL>

      <H2>5. Data Retention</H2>
      <P>
        We retain your information only as long as necessary for the purposes
        described in this policy:
      </P>
      <UL>
        <li>
          <strong>Contact inquiries:</strong> Retained for up to 2 years for
          business correspondence purposes, then deleted.
        </li>
        <li>
          <strong>Reviews:</strong> Retained indefinitely while published on the
          website. Deleted upon request (see Section 7).
        </li>
        <li>
          <strong>Server logs:</strong> Automatically overwritten or purged within
          30 days.
        </li>
      </UL>

      <H2>6. Data Security</H2>
      <P>
        We take reasonable technical and organizational measures to protect your
        personal information, including:
      </P>
      <UL>
        <li>All data is transmitted over HTTPS (TLS encryption).</li>
        <li>
          Form submissions are protected by CSRF tokens to prevent cross-site
          request forgery.
        </li>
        <li>
          Review and contact data is stored in files accessible only to the server
          account, outside public web access.
        </li>
        <li>
          API credentials and sensitive configuration are stored outside the web
          root with restricted file permissions.
        </li>
      </UL>
      <P>
        No method of electronic storage or transmission is 100% secure. While we
        strive to protect your information, we cannot guarantee absolute security.
      </P>

      <H2>7. Your Privacy Rights</H2>
      <H3>California Residents — CCPA / CPRA Rights</H3>
      <P>
        If you are a California resident, you have the following rights under the
        California Consumer Privacy Act (CCPA) and the California Privacy Rights
        Act (CPRA):
      </P>
      <UL>
        <li>
          <strong>Right to Know:</strong> You may request disclosure of the
          categories and specific pieces of personal information we have collected
          about you, the sources, and the purposes for which it is used.
        </li>
        <li>
          <strong>Right to Delete:</strong> You may request deletion of personal
          information we have collected about you, subject to certain exceptions
          (such as completing a transaction or complying with a legal obligation).
        </li>
        <li>
          <strong>Right to Correct:</strong> You may request correction of
          inaccurate personal information we hold about you.
        </li>
        <li>
          <strong>Right to Opt-Out of Sale or Sharing:</strong> We do not sell or
          share your personal information. No opt-out is necessary, but you have
          this right.
        </li>
        <li>
          <strong>Right to Non-Discrimination:</strong> We will not discriminate
          against you for exercising any of your privacy rights.
        </li>
        <li>
          <strong>Right to Limit Use of Sensitive Personal Information:</strong> We
          do not collect sensitive personal information as defined by the CPRA.
        </li>
      </UL>
      <P>
        To exercise any of these rights, please contact us at
        ibingham@compuprotech.com. We will respond to verifiable requests within
        45 days as required by California law. We may need to verify your identity
        before processing your request.
      </P>
      <H3>All Users</H3>
      <P>Regardless of location, you may contact us at any time to:</P>
      <UL>
        <li>Request access to the personal information we hold about you.</li>
        <li>Request correction or deletion of your information.</li>
        <li>
          Withdraw consent for us to contact you (note: this does not apply to
          information required to fulfill an existing service request).
        </li>
      </UL>

      <H2>8. Children's Privacy</H2>
      <P>
        This website is not directed to individuals under the age of 13. We do not
        knowingly collect personal information from children. If you believe we
        have inadvertently collected information from a child under 13, please
        contact us immediately and we will delete it promptly.
      </P>

      <H2>9. Third-Party Links</H2>
      <P>
        This website may contain links to third-party websites (such as email
        links or professional organization pages). We are not responsible for the
        privacy practices of those sites and encourage you to review their privacy
        policies before providing any personal information.
      </P>

      <H2>10. Changes to This Policy</H2>
      <P>
        We may update this Privacy Policy from time to time. When we do, we will
        revise the "Last updated" date at the top of this page. We encourage you
        to review this policy periodically. Continued use of this website after any
        changes constitutes acceptance of the updated policy.
      </P>

      <H2>11. Contact Us</H2>
      <P>
        If you have any questions, concerns, or requests regarding this Privacy
        Policy or the handling of your personal information, please contact:
      </P>
      <P>
        Isela Bingham
        <br />
        FluentLanguage.net
        <br />
        Stockton, California
        <br />
        Email: ibingham@compuprotech.com
      </P>
    </LegalPage>
  )
}
